source 'https://rubygems.org'

gem 'activerecord', require: 'active_record'
gem 'aws-sdk-sqs'
gem 'bcrypt'
gem 'pg'
gem 'pony'
gem 'pry'
gem 'rack-flash3'
gem 'rake'
gem 'require_all', '~> 1.5.0'
gem 'searchkick'
gem 'shoryuken'
gem 'shotgun'
gem 'simplecov'
gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'sinatra-contrib'
gem 'sinatra-static-assets'

group :test, :development do
  gem 'capybara'
  gem 'chromedriver-helper'
  gem 'database_cleaner'
  gem 'factory_bot'
  gem 'faker'
  gem 'rack-test', require: 'rack/test'
  gem 'rack_session_access'
  gem 'rspec'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers'
end
