development:
  adapter: postgresql
  encoding: unicode
  timeout: 10000
  database: weconnect_sinatra
  pool: 40
  username: postgres
  password: <%= ENV['password'] %>

production:
  uri: ENV['DATABASE_URL']

test:
  adapter: postgresql
  encoding: unicode
  database: test_db
  timeout: 10000
  pool: 40
  username: postgres
  password: <%= ENV['password'] %>